--<ScriptOptions statementTerminator=";"/>

CREATE TABLE T_PERSON (
		ID NUMBER(22 , 0) NOT NULL,
		NAME VARCHAR2(12)
	);

CREATE TABLE T_COUNTRY (
		ID NUMBER(22 , 0) NOT NULL,
		NAME VARCHAR2(12)
	);

CREATE TABLE B_DOG (
		ID NUMBER(22 , 0),
		AGE NUMBER(22 , 0)
	);

CREATE TABLE S_RANK (
		ID NUMBER(5 , 0),
		MINSA NUMBER(5 , 0),
		MAXSA NUMBER(5 , 0),
		NAME VARCHAR2(50)
	);

CREATE TABLE U_USER (
		ID NUMBER(22 , 0) NOT NULL,
		NAME VARCHAR2(12),
		SALARY NUMBER(12 , 0),
		BUZHU NUMBER(12 , 0)
	);

CREATE TABLE S_GENDER (
		ID NUMBER(5 , 0) NOT NULL,
		MINSAL NUMBER(7 , 0),
		MAXSAL NUMBER(7 , 0),
		NAME VARCHAR2(20)
	);

CREATE TABLE A_CAT (
		ID NUMBER(22 , 0) NOT NULL,
		NAME VARCHAR2(12),
		COLOR VARCHAR2(12)
	);

CREATE TABLE C_ROLE (
		ID NUMBER(22 , 0) NOT NULL,
		NAME VARCHAR2(12),
		COMMENTS VARCHAR2(12)
	);

CREATE TABLE USER_ROLE (
		U_ID NUMBER(22 , 0) NOT NULL,
		R_ID NUMBER(22 , 0) NOT NULL
	);

CREATE TABLE T_CUSTOMER (
		ID NUMBER(22 , 0) NOT NULL,
		NAME VARCHAR2(12)
	);

CREATE TABLE ROBIN_PRODUCT (
		ID NUMBER(22 , 0) NOT NULL,
		NAME VARCHAR2(25),
		PRICE NUMBER(22 , 0),
		COUNT NUMBER(22 , 0)
	);

CREATE TABLE S_STUDENT (
		ID NUMBER(22 , 0) NOT NULL,
		NAME VARCHAR2(12)
	);

CREATE TABLE T_ORDER (
		ID NUMBER(22 , 0) NOT NULL,
		NAME VARCHAR2(12),
		C_ID NUMBER(22 , 0)
	);

CREATE TABLE TEMP1 (
		COL1 NUMBER(12 , 0),
		CLO2 VARCHAR2(20)
	);

CREATE TABLE TEACHER (
		ID NUMBER(8 , 0) NOT NULL,
		NAME VARCHAR2(12),
		CITY VARCHAR2(12),
		COUNTRY VARCHAR2(12)
	);

CREATE TABLE F_HUSBAND (
		ID NUMBER(22 , 0) NOT NULL,
		NAME VARCHAR2(12)
	);

CREATE TABLE STUDENT (
		ID NUMBER(7 , 0),
		GENDER VARCHAR2(10),
		HEIGHT VARCHAR2(40)
	);

CREATE TABLE T_PASSPORT (
		ID NUMBER(22 , 0) NOT NULL,
		NAME VARCHAR2(2),
		P_ID NUMBER(22 , 0)
	);

CREATE TABLE STU (
		ID NUMBER(10 , 0) NOT NULL,
		NAME VARCHAR2(12)
	);

CREATE TABLE UUID_USER (
		ID VARCHAR2(32)
	);

CREATE TABLE TEST (
		ID NUMBER(22 , 0) NOT NULL,
		NAME VARCHAR2(20) NOT NULL
	);

CREATE TABLE A_DOG (
		ID NUMBER(22 , 0) NOT NULL,
		NAME VARCHAR2(12),
		AGE NUMBER(22 , 0)
	);

CREATE TABLE T_CITY (
		ID NUMBER(22 , 0) NOT NULL,
		NAME VARCHAR2(12),
		P_ID NUMBER(8 , 0)
	);

CREATE TABLE EMP1 (
		ID NUMBER(7 , 0) NOT NULL,
		LAST_NAME VARCHAR2(25) NOT NULL,
		SALARY NUMBER(11 , 2),
		DEPT_ID NUMBER(7 , 0)
	);

CREATE TABLE S_EMP (
		ID NUMBER(7 , 0) NOT NULL,
		LAST_NAME VARCHAR2(25) NOT NULL,
		FIRST_NAME VARCHAR2(25),
		USERID VARCHAR2(8),
		START_DATE DATE,
		COMMENTS VARCHAR2(255),
		MANAGER_ID NUMBER(7 , 0),
		TITLE VARCHAR2(25),
		DEPT_ID NUMBER(7 , 0),
		SALARY NUMBER(11 , 2),
		COMMISSION_PCT NUMBER(4 , 2)
	);

CREATE TABLE PARENTS (
		ID NUMBER(7 , 0) NOT NULL
	);

CREATE TABLE B_ANIMAL (
		ID NUMBER(22 , 0) NOT NULL,
		NAME VARCHAR2(12)
	);

CREATE TABLE H_POLICE (
		ID NUMBER(22 , 0) NOT NULL,
		NAME VARCHAR2(12),
		AGE NUMBER(8 , 2)
	);

CREATE TABLE B_CAT (
		ID NUMBER(22 , 0),
		COLOR VARCHAR2(12)
	);

CREATE TABLE S_REGION (
		ID NUMBER(7 , 0) NOT NULL,
		NAME VARCHAR2(50) NOT NULL
	);

CREATE TABLE S_DEPT (
		ID NUMBER(7 , 0) NOT NULL,
		NAME VARCHAR2(25) NOT NULL,
		REGION_ID NUMBER(7 , 0)
	);

CREATE TABLE S_TEACHER (
		ID NUMBER(22 , 0) NOT NULL,
		NAME VARCHAR2(12)
	);

CREATE TABLE C_USER (
		ID NUMBER(22 , 0) NOT NULL,
		NAME VARCHAR2(12),
		GENDER VARCHAR2(6),
		AGE NUMBER(22 , 0)
	);

CREATE TABLE ANIMAL (
		ID NUMBER(22 , 0) NOT NULL,
		NAME VARCHAR2(12),
		COLOR VARCHAR2(12),
		AGE NUMBER(22 , 0),
		TYPE VARCHAR2(12)
	);

CREATE TABLE P_WIFE (
		ID NUMBER(22 , 0) NOT NULL,
		NAME VARCHAR2(12)
	);

CREATE TABLE P_HUSBAND (
		ID NUMBER(22 , 0) NOT NULL,
		NAME VARCHAR2(12)
	);

CREATE TABLE STU_TEA (
		S_ID NUMBER(22 , 0) NOT NULL,
		T_ID NUMBER(22 , 0) NOT NULL
	);

CREATE TABLE JDBC_USER (
		ID NUMBER(12 , 0) NOT NULL,
		NAME VARCHAR2(16),
		AGE NUMBER(4 , 0)
	);

CREATE TABLE HILO (
		NEXT_VAL NUMBER(22 , 0)
	);

CREATE TABLE F_WIFE (
		ID NUMBER(22 , 0) NOT NULL,
		NAME VARCHAR2(12),
		H_ID NUMBER(22 , 0)
	);

CREATE VIEW V_TEST2 (ID, NAME) 
WITH CASCADED CHECK OPTION;

CREATE VIEW V_TEST1 (ID, NAME) 
WITH CASCADED CHECK OPTION;

CREATE UNIQUE INDEX SYS_C004125 ON STU (ID ASC);

CREATE UNIQUE INDEX SYS_C004147 ON T_ORDER (ID ASC);

CREATE UNIQUE INDEX SYS_C004160 ON T_PASSPORT (ID ASC);

CREATE UNIQUE INDEX SYS_C004126 ON ROBIN_PRODUCT (ID ASC);

CREATE UNIQUE INDEX SYS_C004196 ON C_ROLE (ID ASC);

CREATE UNIQUE INDEX SYS_C004195 ON C_USER (ID ASC);

CREATE UNIQUE INDEX SYS_C004197 ON USER_ROLE (U_ID ASC, R_ID ASC);

CREATE UNIQUE INDEX SYS_C004146 ON T_CUSTOMER (ID ASC);

CREATE UNIQUE INDEX S_DEPT_ID_PK ON S_DEPT (ID ASC);

CREATE UNIQUE INDEX S_EMP_ID_PK ON S_EMP (ID ASC);

CREATE UNIQUE INDEX SYS_C004096 ON TEST (ID ASC);

CREATE UNIQUE INDEX SYS_C004156 ON P_HUSBAND (ID ASC);

CREATE UNIQUE INDEX SYS_C004180 ON S_STUDENT (ID ASC);

CREATE UNIQUE INDEX SYS_C004154 ON F_WIFE (H_ID ASC);

CREATE UNIQUE INDEX SYS_C004186 ON A_DOG (ID ASC);

CREATE UNIQUE INDEX SYS_C004064 ON JDBC_USER (ID ASC);

CREATE UNIQUE INDEX SYS_C004181 ON S_TEACHER (ID ASC);

CREATE UNIQUE INDEX SYS_C004072 ON PARENTS (ID ASC);

CREATE UNIQUE INDEX S_REGION_ID_PK ON S_REGION (ID ASC);

CREATE UNIQUE INDEX S_EMP_USERID_UK ON S_EMP (USERID ASC);

CREATE UNIQUE INDEX SYS_C004182 ON STU_TEA (S_ID ASC, T_ID ASC);

CREATE UNIQUE INDEX SYS_C004208 ON H_POLICE (ID ASC);

CREATE UNIQUE INDEX SYS_C004185 ON ANIMAL (ID ASC);

CREATE UNIQUE INDEX S_DEPT_NAME_REGION_ID_UK ON S_DEPT (NAME ASC, REGION_ID ASC);

CREATE UNIQUE INDEX SYS_C004056 ON S_GENDER (ID ASC);

CREATE UNIQUE INDEX SYS_C004152 ON F_HUSBAND (ID ASC);

CREATE UNIQUE INDEX SYS_C004159 ON T_PERSON (ID ASC);

CREATE UNIQUE INDEX SYS_C004157 ON P_WIFE (ID ASC);

CREATE UNIQUE INDEX SYS_C004144 ON TEACHER (ID ASC);

CREATE UNIQUE INDEX SYS_C004153 ON F_WIFE (ID ASC);

CREATE UNIQUE INDEX SYS_C004161 ON T_PASSPORT (P_ID ASC);

CREATE UNIQUE INDEX SYS_C004187 ON A_CAT (ID ASC);

CREATE UNIQUE INDEX SYS_C004178 ON T_CITY (ID ASC);

CREATE UNIQUE INDEX SYS_C004145 ON U_USER (ID ASC);

CREATE UNIQUE INDEX SYS_C004191 ON B_ANIMAL (ID ASC);

CREATE UNIQUE INDEX SYS_C004163 ON T_COUNTRY (ID ASC);

CREATE UNIQUE INDEX S_REGION_NAME_UK ON S_REGION (NAME ASC);

ALTER TABLE T_CITY ADD CONSTRAINT SYS_C004178 PRIMARY KEY (ID);

ALTER TABLE F_WIFE ADD CONSTRAINT SYS_C004153 PRIMARY KEY (ID);

ALTER TABLE S_STUDENT ADD CONSTRAINT SYS_C004180 PRIMARY KEY (ID);

ALTER TABLE S_REGION ADD CONSTRAINT S_REGION_ID_PK PRIMARY KEY (ID);

ALTER TABLE TEACHER ADD CONSTRAINT SYS_C004144 PRIMARY KEY (ID);

ALTER TABLE USER_ROLE ADD CONSTRAINT SYS_C004197 PRIMARY KEY (U_ID, R_ID);

ALTER TABLE S_GENDER ADD CONSTRAINT SYS_C004056 PRIMARY KEY (ID);

ALTER TABLE P_WIFE ADD CONSTRAINT SYS_C004157 PRIMARY KEY (ID);

ALTER TABLE ANIMAL ADD CONSTRAINT SYS_C004185 PRIMARY KEY (ID);

ALTER TABLE B_ANIMAL ADD CONSTRAINT SYS_C004191 PRIMARY KEY (ID);

ALTER TABLE S_DEPT ADD CONSTRAINT S_DEPT_ID_PK PRIMARY KEY (ID);

ALTER TABLE C_USER ADD CONSTRAINT SYS_C004195 PRIMARY KEY (ID);

ALTER TABLE F_HUSBAND ADD CONSTRAINT SYS_C004152 PRIMARY KEY (ID);

ALTER TABLE ROBIN_PRODUCT ADD CONSTRAINT SYS_C004126 PRIMARY KEY (ID);

ALTER TABLE T_COUNTRY ADD CONSTRAINT SYS_C004163 PRIMARY KEY (ID);

ALTER TABLE PARENTS ADD CONSTRAINT SYS_C004072 PRIMARY KEY (ID);

ALTER TABLE H_POLICE ADD CONSTRAINT SYS_C004208 PRIMARY KEY (ID);

ALTER TABLE P_HUSBAND ADD CONSTRAINT SYS_C004156 PRIMARY KEY (ID);

ALTER TABLE U_USER ADD CONSTRAINT SYS_C004145 PRIMARY KEY (ID);

ALTER TABLE S_TEACHER ADD CONSTRAINT SYS_C004181 PRIMARY KEY (ID);

ALTER TABLE S_EMP ADD CONSTRAINT S_EMP_ID_PK PRIMARY KEY (ID);

ALTER TABLE T_PERSON ADD CONSTRAINT SYS_C004159 PRIMARY KEY (ID);

ALTER TABLE STU_TEA ADD CONSTRAINT SYS_C004182 PRIMARY KEY (S_ID, T_ID);

ALTER TABLE STU ADD CONSTRAINT SYS_C004125 PRIMARY KEY (ID);

ALTER TABLE A_CAT ADD CONSTRAINT SYS_C004187 PRIMARY KEY (ID);

ALTER TABLE C_ROLE ADD CONSTRAINT SYS_C004196 PRIMARY KEY (ID);

ALTER TABLE T_CUSTOMER ADD CONSTRAINT SYS_C004146 PRIMARY KEY (ID);

ALTER TABLE JDBC_USER ADD CONSTRAINT SYS_C004064 PRIMARY KEY (ID);

ALTER TABLE T_ORDER ADD CONSTRAINT SYS_C004147 PRIMARY KEY (ID);

ALTER TABLE TEST ADD CONSTRAINT SYS_C004096 PRIMARY KEY (ID);

ALTER TABLE A_DOG ADD CONSTRAINT SYS_C004186 PRIMARY KEY (ID);

ALTER TABLE T_PASSPORT ADD CONSTRAINT SYS_C004160 PRIMARY KEY (ID);

ALTER TABLE STU_TEA ADD CONSTRAINT SYS_C004184 FOREIGN KEY (T_ID)
	REFERENCES S_TEACHER (ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE B_CAT ADD CONSTRAINT SYS_C004193 FOREIGN KEY (ID)
	REFERENCES B_ANIMAL (ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE B_DOG ADD CONSTRAINT SYS_C004192 FOREIGN KEY (ID)
	REFERENCES B_ANIMAL (ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE T_CITY ADD CONSTRAINT SYS_C004179 FOREIGN KEY (P_ID)
	REFERENCES T_COUNTRY (ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE T_ORDER ADD CONSTRAINT SYS_C004148 FOREIGN KEY (C_ID)
	REFERENCES T_CUSTOMER (ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE USER_ROLE ADD CONSTRAINT SYS_C004199 FOREIGN KEY (R_ID)
	REFERENCES C_ROLE (ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE F_WIFE ADD CONSTRAINT SYS_C004155 FOREIGN KEY (H_ID)
	REFERENCES F_HUSBAND (ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE T_PASSPORT ADD CONSTRAINT SYS_C004162 FOREIGN KEY (P_ID)
	REFERENCES T_PERSON (ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE USER_ROLE ADD CONSTRAINT SYS_C004198 FOREIGN KEY (U_ID)
	REFERENCES C_USER (ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE STU_TEA ADD CONSTRAINT SYS_C004183 FOREIGN KEY (S_ID)
	REFERENCES S_STUDENT (ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE P_WIFE ADD CONSTRAINT SYS_C004158 FOREIGN KEY (ID)
	REFERENCES P_HUSBAND (ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

